# dictionary are use to store data value in key : value 
# a dictionary is a collection which is order changeable and donot allowed dublicate value

# detai={
# "name":"coding technology",
# "address":"balkumari",
# "ward":52,
# "list":[3,4,True,"Ram"]
# }
# x=detai.values()
# print(x)

# a={
#      "name":"coding technology",
# }
# if "l" in a:
#    print("it is in dict")
# else:
#    print("it is not in dict")

# detai={
# "name":"coding technology",
# "address":"balkumari",
# "ward":52,
# }
# detai["city"]="ktm"
# print(detai)


# detai={
# "name":"coding technology",
# "address":"balkumari",
# "ward":52,
# }
# detai.popitem()
# print(detai)

# detai={
# "name":"coding technology",
# "address":"balkumari",
# "ward":52,
# }
# x=detai.clear()
# print(detai)

# family={
#     "child1":{
#      "name":"sunem",
#      "age": 18
#     },
#     "child2":{
#      "name":"silki",
#      "age":15
#     },
#     "child3":{
#      "name":"pallu",
#      "age":2
#     }
# }
# print(family["child1"]["name"])

# child1={
#     "name":"boom",
#     "age":2
# }
# child2={
#     "name":"dodo",
#     "age":2
# }
# child3={
#     "name":"gg",
#     "age":3
# }
# family={
#     "child1":"child1",
#     "child2":"child2",
#     "child3":"child3",
# }
# print(family)

# x=["ten","twenty","thirty"]
# y=[10,20,30]
# z=dict(zip(x,y))
# print(z)

# a={"ten":10,"twenty":20,"thirty":30}
# b={"fourty":40,"fifty":50}
# z=a.copy()
# z.update(b)
# print(z)

# a={"ten":10,"twenty":20,"thirty":30}

# a.pop("twenty")
# print(a)


# a={"ten":10,"twenty":20,"thirty":30}
# for i in a.values():
#     print(i)

# a={"ten":10,"twenty":20,"thirty":30}
# a["fifty"]=a["thirty"]
# print(a)

# a={"ten":10,"twenty":20,"thirty":30}
# print(max(a))

# a={"ten":10,"twenty":20,"thirty":30}
# # print(max(a,values=a.get))
# # print(min(a,values=a.get))
# print(max(a.keys()))

# x=float(45.78924)
# print ("%.2f" %x )

# string="my name is sunem"
# a=string.split()[::-1]
# b=[]
# for i in a:
#     b.append(i)
# print(" ".join(b))





